/**
 * scripts/build-public-catalogs.ts — one machine-owned source for the two public catalogs.
 *
 * The package publishes two enumerable sets: the extensions `package.json#pi.extensions` activates,
 * and the workflow names `extensions/workflows/examples/` resolves. Both were transcribed by hand into
 * docs/extensions.md, docs/workflows.md and two contract tests, and every copy could drift
 * independently — the published "five namespaces" against six on disk was exactly that failure. This
 * script resolves both catalogs from the same readers the runtime uses and writes them once:
 *
 *   dist/public-catalogs.json   checked-in data; contract tests compare reality against it
 *   the fenced regions below    generated Markdown fragments inside published documentation
 *
 * `npm run build:catalogs` writes. `npm run check:generated` (`--check`) regenerates into memory and
 * fails when a committed byte differs, naming the command that fixes it. The check runs inside
 * `npm run check`, so adding or removing an entrypoint or a workflow without regenerating fails the gate.
 *
 * Two boundaries this script does not cross:
 *
 *   It never imports a workflow module. Workflow names come from the same static directory scan the
 *   package registry uses, and each purpose line comes from a bounded static parse of the source text.
 *   Generating documentation must never execute the trusted JavaScript it documents.
 *
 *   It does not re-validate manifests. `scripts/check-extension-manifests.ts` owns the manifest
 *   contract — duplicate ids, duplicate agents, missing docs and test paths, schema conformance. This
 *   script reads the same set through `scripts/extension-manifest-sources.ts` and fails fast, pointing
 *   at that gate, only when a field it consumes is unusable.
 */
import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { staticWorkflowMeta } from "../extensions/workflows/catalog/workflow-meta.js";
import {
  listPackagedWorkflowEntries,
  workflowTargetComposition,
  type PackagedWorkflowEntry,
} from "../extensions/workflows/runtime/workflow-discovery.js";
import { loadedExtensionManifests, type LoadedExtensionManifest } from "./extension-manifest-sources.js";

const CATALOG_FILE = "dist/public-catalogs.json";
const WRITE_COMMAND = "npm run build:catalogs";
const GENERATED_NOTICE = `<!-- Generated by \`${WRITE_COMMAND}\`. Edits between these markers are overwritten. -->`;
const NUMBER_WORDS = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
  "twenty",
];

/**
 * One activated extension, projected from its manifest.
 */
export interface ExtensionCatalogEntry {
  id: string;
  tools: string[];
  commands: string[];
  hooks: string[];
  risk: string;
}

/** One runnable packaged workflow. `namespace` is the owning `<name>/` directory. */
export interface WorkflowCatalogEntry {
  name: string;
  namespace: string;
}

export interface PublicCatalogs {
  extensions: ExtensionCatalogEntry[];
  workflows: WorkflowCatalogEntry[];
}

/** One generated file, addressed by its repository-relative POSIX path. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/** The rendering inputs a fragment needs beyond the catalog data itself. */
interface CatalogSources {
  catalogs: PublicCatalogs;
  /** Extension id to its co-located manual, for the Manual column link. */
  manuals: Map<string, string>;
  /** Workflow name to the one-line purpose its source statically declares. */
  purposes: Map<string, string>;
}

interface DocumentRegion {
  kind: "extensions" | "workflows";
  render: (sources: CatalogSources, docFile: string) => string;
}

interface DocumentTarget {
  file: string;
  regions: DocumentRegion[];
}

/**
 * Where each full catalog lands.
 */
const DOCUMENT_TARGETS: DocumentTarget[] = [
  { file: "docs/extensions.md", regions: [{ kind: "extensions", render: extensionTableFragment }] },
  { file: "docs/workflows.md", regions: [{ kind: "workflows", render: workflowCatalogFragment }] },
];

/** Which catalog regions each published document is expected to carry. Read by the golden test. */
export const GENERATED_DOCUMENTS: ReadonlyArray<{ file: string; kinds: ReadonlyArray<DocumentRegion["kind"]> }> =
  DOCUMENT_TARGETS.map((target) => ({ file: target.file, kinds: target.regions.map((region) => region.kind) }));

if (process.argv[1] && path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1])) {
  await main(process.cwd(), process.argv.slice(2));
}

async function main(root: string, argv: string[]): Promise<void> {
  const unknown = argv.filter((argument) => argument !== "--check");
  if (unknown.length > 0) {
    console.error(`Unsupported argument(s): ${unknown.join(", ")}\nUsage: build-public-catalogs [--check]`);
    process.exitCode = 1;
    return;
  }

  // A defect in the sources — an unreadable manifest, a document whose marker pair was deleted — is a
  // reviewable finding, not a crash. A gate that answers with a Node stack trace tells the reader
  // nothing about which file to open.
  let generated: GeneratedFile[];
  try {
    generated = await generatedPublicCatalogFiles(root);
  } catch (error) {
    console.error(
      `Public catalogs cannot be generated:\n  ${error instanceof Error ? error.message : String(error)}\n` +
        `Fix the source above, then run: ${WRITE_COMMAND}`,
    );
    process.exitCode = 1;
    return;
  }

  if (!argv.includes("--check")) {
    for (const file of generated) {
      const absolute = path.join(root, file.path);
      await mkdir(path.dirname(absolute), { recursive: true });
      await writeFile(absolute, file.content);
    }
    console.log(`Public catalogs written: ${generated.map((file) => file.path).join(", ")}`);
    return;
  }

  const stale = await staleGeneratedFiles(root, generated);
  if (stale.length === 0) {
    console.log(`Public catalogs up to date: ${generated.map((file) => file.path).join(", ")}`);
    return;
  }
  console.error(
    `Generated public catalogs are out of date:\n${stale.map((problem) => `  ${problem}`).join("\n")}\n` +
      `Regenerate them with: ${WRITE_COMMAND}`,
  );
  process.exitCode = 1;
}

/** Every generated file, with the exact bytes a write would produce. */
export async function generatedPublicCatalogFiles(root: string): Promise<GeneratedFile[]> {
  const manifests = loadedExtensionManifests(root);
  const packaged = listPackagedWorkflowEntries();
  const catalogs = publicCatalogs(manifests, packaged);
  const sources: CatalogSources = {
    catalogs,
    manuals: new Map(manifests.map((entry) => [catalogId(entry), stringField(entry, "docsPath")])),
    purposes: await workflowPurposes(packaged),
  };

  const files: GeneratedFile[] = [
    { path: CATALOG_FILE, content: await formatGenerated(root, CATALOG_FILE, JSON.stringify(catalogs)) },
  ];
  for (const target of DOCUMENT_TARGETS) {
    const original = await readFile(path.join(root, target.file), "utf8");
    const rewritten = target.regions.reduce(
      (text, region) => replaceRegion(target.file, text, region.kind, region.render(sources, target.file)),
      original,
    );
    files.push({ path: target.file, content: await formatGenerated(root, target.file, rewritten) });
  }
  return files;
}

/** One line per generated file whose committed bytes differ from a fresh render. */
export async function staleGeneratedFiles(root: string, generated: GeneratedFile[]): Promise<string[]> {
  const stale: string[] = [];
  for (const file of generated) {
    const committed = await readFile(path.join(root, file.path), "utf8").catch(() => undefined);
    if (committed === undefined) stale.push(`${file.path}: is missing`);
    else if (committed !== file.content) stale.push(`${file.path}: differs from the generated content`);
  }
  return stale;
}

/** The catalog data itself: deterministic, ordered by its source readers, and free of prose. */
export function publicCatalogs(
  manifests: LoadedExtensionManifest[],
  packaged: PackagedWorkflowEntry[],
): PublicCatalogs {
  const extensions = manifests.map((entry): ExtensionCatalogEntry => ({
    id: catalogId(entry),
    tools: stringArrayField(entry, "provides", "tools"),
    commands: stringArrayField(entry, "provides", "commands"),
    hooks: stringArrayField(entry, "provides", "hooks"),
    risk: stringField(entry, "risk"),
  }));

  // Discovery already yields a stable order: namespaces sorted, each namespace's root before its
  // sorted children. Re-sorting flat would split one namespace's root from its grouped children.
  const workflows = packaged.map((entry): WorkflowCatalogEntry => ({
    name: entry.name,
    namespace: workflowTargetComposition({ ref: entry.name }).rootRef,
  }));

  assertUnique(
    "extension id",
    extensions.map((entry) => entry.id),
    "run `npm run check:manifests`",
  );
  assertUnique(
    "packaged workflow name",
    workflows.map((entry) => entry.name),
    "rename the colliding entry under extensions/workflows/examples/",
  );
  return { extensions, workflows };
}

/**
 * One purpose line per workflow, from the bounded static scan `/workflows list` already shows operators.
 * The source is read as text and parsed; it is never imported.
 */
async function workflowPurposes(packaged: PackagedWorkflowEntry[]): Promise<Map<string, string>> {
  const purposes = new Map<string, string>();
  for (const entry of packaged) {
    const description = staticWorkflowMeta(await readFile(entry.path, "utf8")).description?.trim();
    if (description === undefined || description === "") {
      throw new Error(
        `Packaged workflow ${entry.name} declares no literal meta.description; ` +
          "the generated catalog has no purpose line to publish",
      );
    }
    purposes.set(entry.name, description);
  }
  return purposes;
}

function extensionTableFragment({ catalogs, manuals }: CatalogSources, docFile: string): string {
  const rows = catalogs.extensions.map((entry) => {
    const manual = manuals.get(entry.id);
    if (manual === undefined) throw new Error(`Extension ${entry.id} has no docsPath to link`);
    return row([
      code(entry.id),
      codeList(entry.tools),
      codeList(entry.commands),
      codeList(entry.hooks),
      cell(entry.risk),
      `[${code(manual)}](${relativeLink(docFile, manual)})`,
    ]);
  });
  return [
    GENERATED_NOTICE,
    "",
    row(["Extension", "Tools", "Commands", "Hooks", "Risk", "Manual"]),
    row(["---", "---", "---", "---", "---", "---"]),
    ...rows,
  ].join("\n");
}

function workflowCatalogFragment({ catalogs, purposes }: CatalogSources): string {
  const namespaces = new Set(catalogs.workflows.map((entry) => entry.namespace));
  const rows = catalogs.workflows.map((entry) =>
    row([code(entry.name), code(entry.namespace), cell(purposes.get(entry.name) ?? "")]),
  );
  return [
    GENERATED_NOTICE,
    "",
    `The registry ships ${numberWord(namespaces.size)} curated Package workflow namespaces ` +
      `with ${numberWord(catalogs.workflows.length)} runnable names.`,
    "",
    row(["Workflow", "Namespace", "Purpose"]),
    row(["---", "---", "---"]),
    ...rows,
  ].join("\n");
}

/**
 * Replace exactly the bytes between one marker pair. A missing, duplicated or inverted marker is a
 * documentation defect this script refuses to guess around, in write mode as much as in check mode.
 */
function replaceRegion(file: string, text: string, kind: DocumentRegion["kind"], body: string): string {
  const start = `<!-- locus:${kind}:start -->`;
  const end = `<!-- locus:${kind}:end -->`;
  const startIndex = markerIndex(file, text, start);
  const endIndex = markerIndex(file, text, end);
  if (endIndex < startIndex) throw new Error(`${file}: ${end} appears before ${start}`);
  return `${text.slice(0, startIndex + start.length)}\n${body}\n${text.slice(endIndex)}`;
}

function markerIndex(file: string, text: string, marker: string): number {
  const first = text.indexOf(marker);
  if (first < 0) throw new Error(`${file}: missing generated-region marker ${marker}`);
  if (text.indexOf(marker, first + marker.length) >= 0) {
    throw new Error(`${file}: generated-region marker ${marker} appears more than once`);
  }
  return first;
}

/**
 * Run the repository formatter over generated output. The generator emits minimal data and lets
 * Prettier own JSON layout and Markdown table padding.
 */
async function formatGenerated(root: string, file: string, text: string): Promise<string> {
  const absolute = path.join(root, file);
  const options = await resolveConfig(absolute);
  return format(text, { ...options, filepath: absolute });
}

/** A published link is only correct relative to the file it is read from, not to the repository root. */
function relativeLink(fromFile: string, target: string): string {
  return path.posix.relative(path.posix.dirname(fromFile), target);
}

function row(cells: string[]): string {
  return `| ${cells.join(" | ")} |`;
}

/** Inline code, with the table-cell separator escaped so a surface name can never split a row. */
function code(value: string): string {
  return `\`${cell(value)}\``;
}

function cell(value: string): string {
  return value.split("|").join("\\|");
}

/** An em dash for an empty surface, matching how the reference tables have always read. */
function codeList(values: string[]): string {
  return values.length === 0 ? "—" : values.map(code).join(", ");
}

/** Published prose spells small counts; anything larger reads better as a numeral than as a word chain. */
function numberWord(count: number): string {
  return NUMBER_WORDS[count] ?? String(count);
}

function catalogId(entry: LoadedExtensionManifest): string {
  return stringField(entry, "id");
}

function stringField(entry: LoadedExtensionManifest, field: string): string {
  const value = entry.manifest[field];
  if (typeof value !== "string" || value === "") {
    throw new Error(`${entry.file}: ${field} must be a non-empty string; run \`npm run check:manifests\``);
  }
  return value;
}

function stringArrayField(entry: LoadedExtensionManifest, group: string, field: string): string[] {
  const parent = entry.manifest[group];
  const value = typeof parent === "object" && parent !== null ? (parent as Record<string, unknown>)[field] : undefined;
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`${entry.file}: ${group}.${field} must be an array of strings; run \`npm run check:manifests\``);
  }
  return value as string[];
}

function assertUnique(subject: string, values: string[], remedy: string): void {
  const seen = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) throw new Error(`Duplicate ${subject}: ${value}; ${remedy}`);
    seen.add(value);
  }
}
